#!/bin/sh

clock="$(cat /proc/cpuinfo | awk '/MHz/ {print $4;exit;}')"
clockimg="💻"
temp="$(sensors | awk '/Core 0/ {print substr($3,2)}')"
tempicon="🌡"
printf "%s %d MHz %s %s\\n" "$clockimg" "$clock" "$tempicon" "$temp"
