#!/bin/sh
userresources=$HOME/.config/X11/Xresources
usermodmap=$HOME/.config/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

[ -f $sysresources ] && xrdb -merge $sysresources
[ -f $sysmodmap ] && xmodmap $sysmodmap
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"
. $HOME/.config/X11/env
xsetroot -cursor_name left_ptr &
sudo $HOME/scripts/powertop_fix.sh &
$HOME/scripts/walli -r &
/bin/emacs --daemon &
#picom &
mpd &
connman-gtk &

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi
exec xmonad
#exec dbus-launch --exit-with-session emacs -mm --debug-init
