#!/bin/sh
userresources=$HOME/.config/X11/Xresources
usermodmap=$HOME/.config/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
wm="dbus-launch emacs -mm --debug-init -l /home/sam/.config/exwm/init-exwm.el "
#wm="/home/sam/.local/share/xmonad/xmonad-x86_64-linux"


if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

[ -f $sysresources ] && xrdb -merge $sysresources
[ -f $sysmodmap ] && xmodmap $sysmodmap
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

xsetroot -cursor_name left_ptr &
xbacklight -set 2% &
sudo $HOME/scripts/powertop.sh &
$HOME/scripts/walli -r &
#/usr/local/bin/emacs --daemon --no-x-resources &
[ $wm = "dwm" ] && dwmblocks &
cmst -m -w 5 &
exec $wm
