#!/bin/sh
wm=xmonad
userresources=$HOME/.config/X11/Xresources
usermodmap=$HOME/.config/X11/Xmodmap
xrdb -merge $userresources
#xmodmap $usermodmap &
#stalonetray -c ~/.config/stalonetrayrc/.stalonetrayrc &
#pasystray &
#nm-applet &
#picom &
xbacklight -set 5 &
sudo $HOME/scripts/powertop_fix.sh &
$HOME/scripts/walli -r &
dunst &
xsetroot -cursor_name left_ptr &
if [ $wm = "dwm" ]; then
    dwmblocks &
fi
exec $wm
