vim.g.dashboard_custom_header = {
'							        ',
'							        ',
'							        ',
'							        ',
'							        ',
'							        ',
'							        ',
'							        ',
'							        ',
' ███╗   ██╗ ███████╗ ██████╗  ██╗   ██╗ ██╗ ███╗   ███╗  ',
' ████╗  ██║ ██╔════╝██╔═══██╗ ██║   ██║ ██║ ████╗ ████║  ',
' ██╔██╗ ██║ █████╗  ██║   ██║ ██║   ██║ ██║ ██╔████╔██║  ',
' ██║╚██╗██║ ██╔══╝  ██║   ██║ ╚██╗ ██╔╝ ██║ ██║╚██╔╝██║  ',
' ██║ ╚████║ ███████╗╚██████╔╝  ╚████╔╝  ██║ ██║ ╚═╝ ██║  ',
' ╚═╝  ╚═══╝ ╚══════╝ ╚═════╝    ╚═══╝   ╚═╝ ╚═╝     ╚═╝  ',
'							        ',
'							        ',
'							        ',
'							        ',
'							        ',
'							        ',
'							        ',
'							        ',
'							        ',
'							        ',
'							        ',
}

vim.g.dashboard_default_executive = 'FZF'
vim.g.dashboard_custom_section = {
   a = {description =  {'  Find file                SPC f f'}, command = 'Files' },
   b = {description =  {'  Recently opened          SPC f r'}, command = 'History' },
   c = {description =  {'  Create new files         SPC f n'}, command = ':new' },
   d = {description =  {'  Search by words          SPC f w'}, command = ':Rg' },
   e = {description =  {'  Edit nvim config         SPC h e'}, command = ':Files ~/.config/nvim' },
   f = {description =  {'  Open vim wiki            SPC w w'}, command = 'VimwikiIndex' },
   g = {description =  {'  Load Last Session        SPC s l'}, command = 'SessionLoad'},
   }
