;; -*- lexical-binding: t; -*-

(add-to-list 'load-path "~/.config/emacs/elisp")

(load "package-manager" nil t)
(load "ui" nil t)
(load "utils" nil t)
(load "theme.el" nil t)
(load "minibuffer" nil t)
(load "editor" nil t)
(load "completion" nil t)
(load "keys" nil t)
(load "file" nil t)
(load "shells" nil t)
(load "lang" nil t)
(load "git.el" nil t)
(load "mail" nil t)
(load "rss" nil t)
(load "chat" nil t)
(load "media" nil t)
(load "org-mode" nil t)
(load "passwords" nil t)
