;; -*- lexical-binding: t; -*-

(add-to-list 'load-path "~/.config/emacs/elisp")

(load-library "ui")
(load-library "package-manager")
(load-library "utils")
(load-library "theme.el")
(load-library "minibuffer")
(load-library "editor")
(load-library "completion")
(load-library "keys")
(load-library "file")
(load-library "lang")
(load-library "git.el")
(load-library "mail")
(load-library "rss")
(load-library "chat")
(load-library "org-mode")
(load-library "passwords")
