#!/bin/sh

SC_DIR=~/external/hdd2/screenshots/
NAME="$(date +%d-%m-%Y-%I:%M:%p).png"
[ $1 = "-r" ] && NAME="$(echo "" | dmenu -p 'name :').png"

case $2 in
      # screenshots select
     -s)
	maim -s $SC_DIR/$NAME
	;;
      # screenshots focused window
     -w)
     maim -i $(xdotool getactivewindow) $SC_DIR/$NAME
	;;
      # copies entire screen
     -c)
	maim | xclip -selection clipboard -t image/png
	;;
      # copies focused window to clipboard
     -cw)
	maim -i $(xdotool getactivewindow) | xclip -selection clipboard -t image/png
	;;
      # copies selected window to clipboard
     -cs)
	maim -s | xclip -selection clipboard -t image/png
	;;
      # gives rgb values of select pixel
     -r)
	maim -st 0 | convert - -resize 1x1\! -format '%[pixel:p{0,0}]' info:-
	;;
      # full screenshots
     *)
	maim $SC_DIR/$NAME
	;;
esac
