#!/bin/sh

[ ! -d /home/$USER/.config/walli ] && mkdir /home/$USER/.config/walli
[ ! -f /home/$USER/.config/walli/wallpaper ] && touch /home/$USER/.config/walli/wallpaper

WALL_DIR=~/external/hdd2/walls
OPT="${2:---stretch}"
case $1 in
    -r)
	cat $HOME/.config/walli/wallpaper | xargs xwallpaper --stretch
	;;
    *)
	SELECTED=$(sxiv -o -q -r -t $WALL_DIR)
	[ "$SELECTED" = "" ] && exit
	echo $SELECTED > ~/.config/walli/wallpaper
	xwallpaper $OPT $SELECTED
	;;
esac
